### ISSUE TITLE
URL links in Outlook default to incorrect desktop browser

### ISSUE THREAD

**Issue by Chobbletto** [sirredbeard/unofficial-webapp-office#16]
Hi there,
Thanks for your hard work!
Clicking a link within an email in Outlook tried to run a Wine app (internet explorer I assume) rather than the default browser, Firefox in my case on KDE Neon 5.17.

Any way around this?

**Comment by sirredbeard** [comment]
Any non-Office related links should be opened in your default browser on your desktop. There is no Wine, IE, or anything like that installed in unofficial-webapp-office, that is odd. Maybe try resetting your default browser in Plasma to Firefox?

**Comment by Chobbletto** [comment]
Cheers Hayden,

That was the problem, and nothing to do with your work!

Really appreciate the help and the effort you've put into this snap!

All the best.
