### ISSUE TITLE
Cannot create new document

### ISSUE THREAD

**Issue by acestronautical** [sirredbeard/unofficial-webapp-office#21]
Clicking New Blank Document does nothing. This seems to effect all word, powerpoint, excel, etc....

![Screenshot from 2020-05-02 13-52-11](https://user-images.githubusercontent.com/18414941/80892037-e2600b80-8c7c-11ea-8239-d8dff4f7461a.png)

I installed unofficial-webapp-office through the snap store on Ubuntu 20.04. I do not have chrome installed. I sign into office365 via my schools SSO authentication (I think that's what it's called).

![Screenshot from 2020-05-02 14-00-21](https://user-images.githubusercontent.com/18414941/80892260-83e75d00-8c7d-11ea-96dc-5521d411241f.png)
(ignore the --version flag in the command, that was a mistake and doesn't do anything. Clicking new document triggers the ""about" is not allowed" error.)

Thank you for all your hard work and please keep at it. Linux sorely needs some sort of MS Office solution, and if this manages to become a solid app then that is a big win for Linux. In fact I'm waiting right now to switch one of my friends laptops over to Ubuntu, but I don't want to do so until this app is up to par. (Yes I know they could just use office365 in browser, but for some reason that scares people)

**Comment by sirredbeard** [comment]
I think there is an issue with student accounts. #19

**Comment by alievrouw** [comment]
I'm seeing the same behavior as well. I have a work account. How can I troubleshoot this?
