### ISSUE TITLE
The applications on Ubuntu is shown under "Other" category and keywords are not working

### ISSUE THREAD

**Issue by furkanarabaci** [sirredbeard/unofficial-webapp-office#9]
E.g at [excel.desktop](https://github.com/sirredbeard/unofficial-webapp-office/blob/master/snap/gui/excel.desktop), categories are set but separated by comma instead of semicolon.

Also, it should be "keywords" instead of "keyworks"

**Comment by sirredbeard** [comment]
Thank you for the PR. Testing it now.
